name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/DevHabitApi

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore DevHabitApi.sln

      - name: Build
        run: dotnet build DevHabitApi.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test DevHabitApi.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish DevHabitApi.sln --configuration Release --no-restore --no-build
